version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./certs:/etc/nginx/certs
  